[project]
name = "tasks4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.0",
]

[dependency-groups]
dev = [
    "pytest>=9.0.1",
]
